### ISSUE TITLE
Question——For——FindDuplicate

### ISSUE THREAD

**Issue by klvoek** [ligong/lgmisc#1]
求科普while循环的思想依据。  
我瞪了几个小时，现在觉得这个循环是将整串数组按index排序  
比如一种情况 01234566 。到第一个6之前，while a[i] != i 一直不成立。 内层的 a[i] == a[a[i]] 也是 a[i] == i 的判断。这个是根据已知实现和结果去反推。  
求设计之前的思路和想法。

**Comment by ligong** [comment]
设计前的主要思路就是注释写的那样。

这个while循环作用是确保把a[i]放到正确的位置上。对于例子[0,1,2,3,4,5,6,6],  i = 0..6 时， a[i]都是在正确的位置上(即a[i] == i), 所以while循环里面的swap不会被执行, 当i == 7, 发现重复，返回结果。

 换一个例子[5,1,2,0,4,3,6,6], 当for循环的i == 0时， while循环发现a[0]!=0, 交换 a[0]和a[5], 也就是把a[5]换到它正确的位置5上去，数组变成[3,1,2,0,4,5,6,6],  又发现a[0]!=0, 交换a[0]和a[3], 把a[3]放到了正确位置3上，数组变成[0,1,2,3,4,5,6,6], 这次发现a[0]是正确位置了，while循环终止，回到for循环, 增加i。

每次执行while循环中的swap, 都会把一个元素放到正确的位置上。 由于一开始最多只有n个元素不在自己的位置上， while循环最多执行n次, 满足题目要求。

**Comment by klvoek** [comment]
也就是把a[5]换到它正确的位置5上去。这句话就理解了。 Thanks
